### ISSUE TITLE
Running Truffle tests "Unexpected token"

### ISSUE THREAD

**Issue by mikedotexe** [aave/aave-protocol#21]
Trying to get Truffle to run tests and continue to get:
```
SyntaxError: /Users/mike/near/aave-protocol/test/actions/index.ts: Unexpected token (44:2)
  42 |
  43 | const almostEqualOrEqual = function(
> 44 |   this: any,
     |   ^
  45 |   expected: ReserveData | UserReserveData,
  46 |   actual: ReserveData | UserReserveData
  47 | ) {
    at Parser.pp$5.raise (/Users/mike/near/aave-protocol/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/mike/near/aave-protocol/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$2.parseBindingAtom (/Users/mike/near/aave-protocol/node_modules/babylon/lib/index.js:3090:12)
```

Updated typescript to:
`"typescript": "^4.0.2"`

Would be great to get some help running the tests. Cheers
Tried node 12, 11
Truffle 5.1.43

**Comment by paulvi** [comment]
see also #16
