### ISSUE TITLE
Kovan + LINK + Lending - deposit() | UnhandledPromiseRejectionWarning: Error: VM execution error 

### ISSUE THREAD

**Issue by anupam-io** [aave/aave-protocol#47]
I am trying to use the lending feature of AAVE. I was successful using `ETH` & `aETH`. 
But I am facing issues with `LINK`.

Following is the error I am getting:
```
Attempting to deploy from account  0x3D356DCBAc29e69a7fc237f45F8318E099268a0e
lpAddress found:  0xE0fBa4Fc209b4948668006B2bE61711b7f465bAe
(node:19131) UnhandledPromiseRejectionWarning: Error: VM execution error.
Reverted 0x
    at Object._fireError (/home/pam/aave-testing/node_modules/web3-utils/lib/index.js:50:17)
    at sendTxCallback (/home/pam/aave-testing/node_modules/web3-core-method/lib/index.js:540:30)
    at /home/pam/aave-testing/node_modules/web3-core-requestmanager/lib/index.js:300:20
    at /home/pam/aave-testing/node_modules/@trufflesuite/web3-provider-engine/index.js:238:9
    at /home/pam/aave-testing/node_modules/@trufflesuite/web3-provider-engine/node_modules/async/internal/once.js:12:16
    at replenish (/home/pam/aave-testing/node_modules/@trufflesuite/web3-provider-engine/node_modules/async/internal/eachOfLimit.js:61:25)
    at /home/pam/aave-testing/node_modules/@trufflesuite/web3-provider-engine/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/home/pam/aave-testing/node_modules/@trufflesuite/web3-provider-engine/node_modules/async/eachLimit.js:43:36)
    at /home/pam/aave-testing/node_modules/@trufflesuite/web3-provider-engine/node_modules/async/internal/doLimit.js:9:16
    at end (/home/pam/aave-testing/node_modules/@trufflesuite/web3-provider-engine/index.js:217:5)
    at Request._callback (/home/pam/aave-testing/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:70:28)
    at Request.self.callback (/home/pam/aave-testing/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/pam/aave-testing/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/pam/aave-testing/node_modules/request/request.js:1076:12)
(node:19131) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19131) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
[Deploy script](https://github.com/chainlink-hackathon-team/aave-testing/blob/00189e1cc91d12130235770cfaab555708168c61/1_deploy.js)
[Full code link](https://github.com/chainlink-hackathon-team/aave-testing/tree/00189e1cc91d12130235770cfaab555708168c61)

Can someone tell me what I am doing wrong?

**Comment by anupam-io** [comment]
- I have to call the `ERC20` functions
 - Also, download the latest ABI files
